services:

  postgres:
    image: postgres:18
    container_name: hotelbooking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: HotelBooking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: