<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HotelBooking.Domain\HotelBooking.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Admin\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.30" />
      <PackageReference Include="Scrutor" Version="5.0.0" />
    </ItemGroup>

</Project>
