<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HotelBooking.Application\HotelBooking.Application.csproj" />
        <ProjectReference Include="..\HotelBooking.Domain\HotelBooking.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Persistence\Migrations\" />
        <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CloudinaryDotNet" Version="1.29.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.31" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
        <PackageReference Include="Stripe.net" Version="52.4.2" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    </ItemGroup>

</Project>
